import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Cairo } from "next/font/google";

const cairo = Cairo({
  weight: ["300", "400", "500"],
  subsets: ["latin"],
});

export const metadata = {
  title: "World App",
  description: "Generated by Mspano",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cairo.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
