import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "World App",
  description: "Generated by Mspano",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul>
            <li>
              <Link href="/">All</Link>
            </li>
            <li>
              <Link href="/europe">Europe</Link>
            </li>
            <li>America</li>

            <li>Africa</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
